### ISSUE TITLE
Not show 'todos' in home page

### ISSUE THREAD

**Issue by daab** [tastycrayon/sveltekit-pocketbase-auth#1]
- Not show 'todos' in home page. 
- In PageData only exist data of user. 
lin 4 in page.svelte: 
        export let data: PageData; // received todo from +page.ts  
- Not exist page.ts

**Comment by daab** [comment]
Unfortunately I did not realize that the problem is authentication. In pocketbase the following message is displayed: "errorMessage": "Only admins can perform this action.", which changes the situation.

**Comment by tastycrayon** [comment]
> Unfortunately I did not realize that the problem is authentication. In pocketbase the following message is displayed: "errorMessage": "Only admins can perform this action.", which changes the situation.

Which data are you fetching? 
![image](https://github.com/tastycrayon/sveltekit-pocketbase-auth/assets/37541747/8bb7b568-7e63-40f7-b71f-9b3ebc8b1e53)
Have you enabled permission from pocketbase?
